steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - combine_security_rules
      - --source=https://source.cloud.google.com/uri-test/github_urikatsirprivate_cloud-armor/
      - --trigger-http
      - --runtime=python37
