steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - combine_security_rules
      - --source=https://source.developers.google.com/projects/uri-test/repos/github_urikatsirprivate_cloud-armor
      - --trigger-http
      - --runtime=python37
